//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrozenFoods.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddProductHistory : BaseEntity
    {
       
        public string ProductId { get; set; }
        public string ProductName { get; set; }
        public string AddedBy { get; set; }
        public int AddedQuantity { get; set; }
      
    }
}
