//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrozenFoods.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem : BaseEntity
    {
      
        public string OrderId { get; set; }
        public int OrderNumberForign { get; set; }
        public string ProductId { get; set; }
        public string ProductName { get; set; }
        public decimal Price { get; set; }
        public string Image { get; set; }
        public int Quantity { get; set; }
       
        public virtual Order Order { get; set; }
    }
}
