//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrozenFoods.Core.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ProductCategory : BaseEntity
    {
        [Required]
        [StringLength(20, ErrorMessage = "The Category must be less than 20 letters.")]
        public string Category { get; set; }

        [Required]
        public bool IsActive { get; set; }
       
    }
}
