//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrozenFoods.Core.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Product : BaseEntity
    {

        [DisplayName("Product Name")]
        [StringLength(20, ErrorMessage = "The characters must be less than 20 characters.")]
        public string Name { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The characters must be less than 100 characters.")]
        public string Description { get; set; }

        [Required]
        public string Category { get; set; }

        [Required]
        [RegularExpression(@"^([0-9]*)", ErrorMessage = "Invalid Value.")]
        public int TotalQuantity { get; set; }
        public int Unit { get; set; }

        [Required]
        [RegularExpression(@"^([0-9]*)", ErrorMessage = "Invalid Value.")]
        public decimal Price { get; set; }
        public string Image { get; set; }

    }
}
